In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
a = np.arange(5)

In [4]:
type(a)

numpy.ndarray

In [5]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int64')

In [8]:
a

array([0, 1, 2, 3, 4])

In [9]:
a.shape

(5,)

In [10]:
m = np.array([np.arange(2), np.arange(2)])

In [11]:
m

array([[0, 1],
       [0, 1]])

In [12]:
m.shape

(2, 2)

In [13]:
n = np.array([np.arange(3), np.arange(3), np.arange(3)])

In [14]:
n

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [15]:
n.shape

(3, 3)

In [3]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
sum0 = np.sum(a, axis=0)
sum1 = np.sum(a, axis=1)

In [4]:
print(sum0)
print(sum1)

[4 6]
[3 7]
